config/routes.rb
Rails.application.routes.draw do
  devise_for :walkers
  devise_for :users
  scope 'meu-perfil' do
    resources :dogs, only: [:new, :create]
  end
  root to: 'home#index'
  resources :walkers, only: [:show] do
    resources :proposals, only: [:new, :create, :index] do
      member do
        post :approve
        post :refuse
      end
    end
  end
  post 'proposals/:id/rate', to: 'proposals#rate', as: 'rate_proposal'
  get '/search/', to: 'walkers#search'
  get '/meu-perfil', to: 'profiles#my_profile', as: 'my_profile'
  get '/profile/:id', to: 'profiles#show', as: 'profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :name, :age, :size, :race, :personality, presence: true
  belongs_to :user
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
  belongs_to :walker
  validates :days, :hours, :dogs, :gang, :location, presence: true
  enum status: { pending: 0, approved: 1, refused: 2 }
end

app/models/region.rb
class Region
  REGION = %w(Norte Sul Leste Oeste Centro).freeze
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dogs
  has_many :proposal
  has_many :walkers, through: :proposal
end

app/models/walker.rb
class Walker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :age, :address, :cpf, :bio, :experience, :price, :email,
            :phone, :region, presence: true
  has_many :proposal
  has_many :users, through: :proposal
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' },
                     default_url: 'dog.jpg'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    if resource_class == Walker
      devise_parameter_sanitizer.permit(:sign_up, keys:
                                       [:name, :age, :address, :cpf, :bio,
                                        :experience, :price, :phone,
                                        :region, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys:
                                        [:age, :address, :bio,
                                         :experience, :price, :phone,
                                         :region, :avatar])

    elsif resource_class == User
      devise_parameter_sanitizer.permit(:sign_up, keys:
                                       [:name, :address, :cpf, :phone])
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :authenticate_user!

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user_id = current_user.id

    if @dog.save
      flash[:notice] = 'Seu cão foi adicionado ao seu perfil.'
      redirect_to my_profile_path
    else
      render :new
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :age, :size,
                                :race, :personality, :avatar)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @walkers = Walker.all
    @regions = Region::REGION
    flash[:alert] = 'Não temos nenhum walker cadastrado'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_walker!, only: [:show, :edit_walker]
  before_action :authenticate_user!, only: [:my_profile]

  def my_profile
    @user = current_user
    @proposals = Proposal.where(user_id: current_user.id)
    render :show
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
    @walker = Walker.find(params[:walker_id])
    @proposals = Proposal.where(walker_id: @walker.id)
  end

  def new
    @walker = Walker.find(params[:walker_id])
    @proposal = Proposal.new
    @user = current_user
  end

  def create
    @proposal = Proposal.new(proposal_params)
    @walker = Walker.find(params[:walker_id])
    @proposal.walker_id = @walker.id
    @proposal.user_id = current_user.id
    if @proposal.save
      flash[:notice] = 'Proposta enviada! Aguarde a resposta.'
      redirect_to root_path
    else
      render :new
    end
  end

  def approve
    proposal = Proposal.find_by(params[:walker_id], params[:id])
    proposal.approved!
    flash[:notice] = "Compromisso marcado para #{proposal.days}"
    redirect_to walker_proposals_path(params[:walker_id])
  end

  def refuse
    proposal = Proposal.find_by(params[:walker_id], params[:id])
    proposal.refused!
    flash[:notice] = 'A proposta foi recusada'
    redirect_to walker_proposals_path(params[:walker_id])
  end

  def rate
    proposal = Proposal.find(params[:id])
    proposal.rating = params[:rating]
    proposal.save
    redirect_to my_profile_path
  end

  private

  def proposal_params
    params.require(:proposal).permit(:user_id, :walker_id, :days, :hours,
                                     :dogs, :gang, :location, :observation)
  end
end

app/controllers/walkers_controller.rb
class WalkersController < ApplicationController
  def show
    @walker = Walker.find(params[:id])
  end

  def search
    @walkers = Walker.where(region: params[:region])
    @regions = Region::REGION
    @region = params[:region]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/new.html.erb
<section class='create-dog'>
  <h2>Adicionar Cachorro</h2>

  <%= simple_form_for @dog do |f|%>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :age %>
      <%= f.input :size %>
      <%= f.input :race %>
      <%= f.input :personality %>
      <%= f.input :avatar, as: :file, label: 'Adicionar imagem' %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, 'Salvar', class: "button primary" %>
    </div>
  <% end %>
</section>

app/views/home/index.html.erb
<section id='about'>
  <p class='intro'>
    Encontre pessoas especializadas para passear com seu melhor amigo próximas a você
  </p>
</section>
<% if @walkers.empty? %>
  <%= flash[:alert] %>
<% else %>
  <section class='search'>
    <div class='autocomplete'>
      <%= form_tag("/search/", method: 'get') do%>
        <%= label_tag(:region, 'Onde você está?')%>
        <%= select_tag(:region, options_for_select(@regions)) %>
        <%= submit_tag('Procurar') %>
      <% end %>
    </div>
  </section>
<% end %>
<% unless user_signed_in? || walker_signed_in? %>
  <section class="sign-up">
    <%= link_to 'Se cadastre como dono', new_user_registration_path,
    class: "button primary", role: "button"%>
    <%= link_to 'Se cadastre como walker!', new_walker_registration_path,
      class: "button primary red", role: "button" %>
  </section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TheWalkingDog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>" data-path="<%= request.fullpath %>">
    <div class="overlay"></div>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to(root_path, class: "navbar-brand") do %>
            The Walking Dog <i class="fa fa-paw" aria-hidden="true"></i>
          <% end %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><span>Olá, <%= current_user.name %></span></li>
              <li><%= link_to 'Meu perfil', my_profile_path, class: "button secondary yellow", role: "button" %></li>
              <li><%= link_to 'logout', destroy_user_session_path, class: "button secondary", role:'button', method: :delete %></li>
            <% elsif walker_signed_in? %>
              <li><span>Olá, <%= current_walker.name %></span></li>
              <li><%= link_to 'Meu perfil',  walker_path(current_walker), class: "button secondary red", role: "button" %></li>
              <li><%= link_to 'Minhas propostas', walker_proposals_path(current_walker), class: "button secondary red", role: "button" %></li>
              <li><%= link_to 'logout', destroy_walker_session_path, class: "button secondary red", role:'button', method: :delete %></li>
            <% else %>
              <li><%= link_to 'login como dono', new_user_session_path , class: "button secondary", role: "button"%></li>
              <li><%= link_to 'login como walker', new_walker_session_path , class: "button secondary red", role: "button"%></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  <div class='container'>
    <%= render 'shared/flash' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/profiles/my_profile.html.erb
<section class='profile'>
  <h3><%= @user.name %></h3>

  <%= link_to 'Cadastrar Cachorro', new_dog_path, role: 'button'%>

</section>
<section class='dogs'>
  <% if @user.dogs.empty? %>
    <p>Você ainda não cadastrou nenhum cachorro =(</p>
  <% else %>
    <% @user.dogs.each do |dog| %>
      <div class="jumbotron">
        <%= image_tag dog.avatar.url(:thumb) %>
        <p><%= dog.name %></p>
        <p><%= dog.age %> anos</p>
        <p><%= dog.size %></p>
        <p><%= dog.race %></p>
        <p><%= dog.personality %></p>
      </div>
    <% end %>
  <% end %>
</section>

app/views/profiles/show.html.erb
<header class="header">
  <% if current_user == @user %>
  <%= link_to 'Cadastrar Cachorro', new_dog_path(@user), class: "button primary" %>
  <% end %>
</header>
<section class="profile">
  <h1><%= @user.name %></h1>
  <div class="data">
    <dl>
      <dt class="label">Endereço</dt>
      <dd>
        <%= @user.address %>
      </dd>
    </dl>
  </div>
  <div class='dogs'>
    <% if @user.dogs.empty? %>
      <% if @user == current_user %>
        <p>Você ainda não cadastrou nenhum cachorro =(</p>
      <% else %>
        <p>Nenhum cachorro foi cadastrado. :(</p>
      <% end %>
    <% else %>
      <% @user.dogs.each do |dog| %>
        <div class="jumbotron cols">
          <div class="col">
            <%= image_tag dog.avatar.url(:thumb) %>
          </div>
          <div class="col">
            <h2><%= dog.name %></h2>
            <div class="data">
              <dl>
                <dt class="label">Idade</dt>
                <dd>
                  <%= dog.age %> anos
                </dd>
                <dt class="label">Porte</dt>
                <dd>
                  <%= dog.size %>
                </dd>
                <dt class="label">Raça</dt>
                <dd>
                  <%= dog.race %>
                </dd>
                <dt class="label">Personalidade</dt>
                <dd>
                  <%= dog.personality %>
                </dd>
              </dl>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
</section>

<% if @user == current_user %>
  <section class='proposals'>
    <h1>Minhas propostas</h1>
    <% if @proposals.empty? %>
      <p>Você não enviou propostas</p>
    <% else %>
      <div class="jumbotron cols">
        <% @proposals.each do |proposal| %>
          <div class="data">
            <dl>
              <dt class="label">Nome</dt>
              <dd>
                <%= proposal.walker.name %>
              </dd>
              <dt class="label">Cães</dt>
              <dd>
                <%= proposal.dogs %>
              </dd>
              <dt class="label">Dias</dt>
              <dd>
                <%= proposal.days %>
              </dd>
              <dt class="label">Período</dt>
              <dd>
                <%= proposal.hours %>
              </dd>
              <dt class="label">Status</dt>
              <% if proposal.pending? %>
                <dd>Aguardando resposta</dd>
              <% elsif proposal.refused? %>
                <dd>Proposta recusada</dd>
              <% elsif proposal.approved? %>
                <dd>
                  Proposta aceita
                  <% if proposal.rating %>
                    <p>Nota: <%= proposal.rating %></p>
                  <% else %>
                    <p>Avalie o walker!</p>
                    <%= form_tag(rate_proposal_path(proposal), method: 'post') do %>
                      <%= radio_button_tag(:rating, "1") %>
                      <%= label_tag(:rating_1, "1") %>
                      <%= radio_button_tag(:rating, "2") %>
                      <%= label_tag(:rating_2, "2") %>
                      <%= radio_button_tag(:rating, "3") %>
                      <%= label_tag(:rating_3, "3") %>
                      <%= radio_button_tag(:rating, "4") %>
                      <%= label_tag(:rating_4, "4") %>
                      <%= radio_button_tag(:rating, "5") %>
                      <%= label_tag(:rating_5, "5") %>
                      <%= submit_tag('Enviar nota') %>
                    <% end %>
                  <% end %>
                </dd>
              <% end %>
            </dl>
          </div>



        <% end %>
      </div>
    <% end %>
  </section>
<% end %>

app/views/proposals/index.html.erb
<section class='proposals'>
  <h2>Minhas propostas</h2>
  <% unless  @proposals.empty? %>
    <% @proposals.each do |proposal| %>
      <div class="proposal jumbotron">
        <p>Dono: <%= proposal.user.name %></p>
        <p>Cães: <%= proposal.dogs %></p>
        <p>Dias: <%= proposal.days %></p>
        <p>Período: <%= proposal.hours %></p>
        <p>Local: <%= proposal.location %></p>
        <p>Tipo de passeio: <%= proposal.gang %></p>
        <p>Observação: <%= proposal.observation %></p>

        <% if proposal.pending? %>
          <%= link_to 'Aceitar',
             approve_walker_proposal_path(@walker, proposal),
              {role:'button', method: :post}%>
          <%= link_to 'Recusar',
              refuse_walker_proposal_path(@walker, proposal),
              {role:'button', method: :post}%>
        <% elsif proposal.approved? %>
          <p>Proposta aceita</p>
        <% elsif proposal.refused? %>
          <p>Proposta recusada</p>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>Você ainda não tem propostas</p>
  <% end %>
</section>

app/views/proposals/new.html.erb
<section class='new-proposal'>
  <h2>Nova proposta</h2>
  <%= simple_form_for [@walker, @proposal] do |f| %>
    <div class="form-inputs">
      <%= f.input :days, collection: %w(Segunda-feira Terça-feira Quarta-feira Quinta-feira Sexta-feira Sábado Domingo),label: 'Dias' %>
      <%= f.input :hours, collection: %w(Manhã Tarde Noite),label: 'Período' %>
      <%= f.input :dogs, collection: current_user.dogs, label: 'Nome do cão' %>
      <%= f.input :gang,
          collection: %w(Individual Grupo),
          label: 'Tipo de passeio' %>
      <%= f.input :location, label: 'Localização' %>
      <%= f.input :observation, label: 'Observações' %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, 'Enviar', class: "button primary red" %>
    </div>
  <% end %>
</section>

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% elsif flash[:notice] %>
      <p class="alert"><%= flash[:notice] %></p>
  <% elsif flash[:success] %>
    <p class="success"><%= flash[:success] %></p>
  <% end %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/walkers/search.html.erb
<div class='autocomplete' data-context="secondary">
  <%= form_tag("/search/", method: 'get') do%>
    <%= label_tag(:region, 'Filtrar walkers')%>
    <%= select_tag(:region, options_for_select(@regions)) %>
    <%= submit_tag('Procurar') %>
  <% end %>
</div>

<section class='walkers'>
  <h1>Walkers na região <%= @region %></h1>
  <% @walkers.each do |walker| %>
    <div class="walker cols person_item">
      <div class="col thumb">
        <%= image_tag walker.avatar.url(:thumb) %>
      </div>
      <div class="col data">
        <h1><%= walker.name %></h1>
        <p class="row aside">
          <span class="region"><%= walker.region %></span> | <span class="price">R$<%= walker.price %> / h</span>
        </p>
        <p class="row">
          <%= link_to 'Saiba mais', walker, class: "button secondary red"%>
        </p>
      </div>
    </div>

  <% end %>
</section>

app/views/walkers/show.html.erb
<header class="header">
  <% if user_signed_in? %>
    <%= link_to 'Enviar proposta', new_walker_proposal_path(@walker), class: "button primary red" %>
  <% end %>
</header>
<section class="profile">
  <h1><%= @walker.name %></h1>
  <p class="row aside">
    <span class="region"><%= @walker.region %></span> | <span class="price">R$<%= @walker.price %> / h</span>
  </p>
  <div class="data">
    <dl>
      <dt class="label">Idade</dt>
      <dd>
        <%= @walker.age %>
      </dd>
      <dt class="label">Experiência</dt>
      <dd>
        <%= @walker.experience %>
      </dd>
      <dt class="label">Bio</dt>
      <dd>
        <%= @walker.bio %>
      </dd>
    </dl>
  </div>
  <% if current_walker == @walker %>
    <%= link_to 'Editar perfil', edit_walker_registration_path(@walker), class: "button primary red" %>
  <% end %>
</section>